```{r}
require("functional")
require("dplyr")
```

```{r load_data}
#Loading the data
appData <-
	read.csv(
		 unz("data/noshowappointments.zip", "KaggleV2-May-2016.csv"),
		 header=TRUE)

# Computing the wait
schedDay <- const (
	sapply(X = (appData$ScheduledDay %>% as.character %>% strsplit("T")),
	       FUN=`[[`, 1) %>%
	strptime("%Y-%m-%d") %>% as.Date)


appDay <- const (
	sapply(X = (appData$AppointmentDay %>% as.character %>% strsplit("T")),
	       FUN=`[[`, 1) %>%
	strptime("%Y-%m-%d") %>% as.Date)

appData$Wait= (appDay() - schedDay()) %>% as.numeric #in days
appData$ScheduledDay = schedDay()
appData$AppointmentDay = appDay()

# Data clean up
appData <- appData[appData$Wait>=0,]
appData <- appData[appData$Age>=0,]
```

## Training a Tree model

```{r}
require("party")
treeModel <- ctree(No.show ~ Wait + SMS_received + Age + Scholarship + Gender,
		   data=appData, control=ctree_control(minbucket=5000))
summary(treeModel)
plot(treeModel)

range(appData$ScheduledDay)
range(appData$AppointmentDay)

# Predict probabilities from the model
pred <- Predict(treeModel, appData[1:5000,], type="prob")

prop.table(table(appData$No.show))

prob <- matrix(unlist(pred),ncol=2,byrow=TRUE)[,2]


```
